PHRASES = {
    'Serbian': {
        'welcome': 'Добродошли у бот за струју у Београду!\nИзаберите језик\n',
        'choose_action': 'Изаберите акцију',
        'enter_address': 'Молимо вас да унесете адресу',
        'enter_area': 'Молимо вас да унесете вашу област (нпр. земун)',
        'enter_street': 'Молимо вас да унесете вашу улицу',
        'enter_house': 'Молимо вас да унесете ваш број куће:',
        'summary': 'Ваша пуна адреса',
        'subscribed': 'Добијаћете обавештења на следеће адресе:',
        'list_addresses': 'Приказујемо све ваше адресе',
        'delete_address': 'Коју адресу желите да обришете?)',
        'bye': 'Збогом! Надам се да ћемо поново разговарати ускоро.',
        'invalid_language': 'Изабрани језик није валидан. Покушајте поново.',
        'invalid_input': 'Невалидан унос. Унесите валидан број.',
        'enter_number_delete': 'Молимо вас да унесете број адресе коју желите да обришете.',
        'address': 'Адреса',
        'was_deleted': 'је обрисана.',
        'address_scheduled_tomorrow': 'На овој адреси сутра ће бити искључена струја.',
        'cancel': 'Откажи',
    },
    'English': {
        'welcome': 'Welcome to the Beograd Electricity Bot!\nChoose your language\n',
        'choose_action': 'Please choose an action',
        'enter_address': 'Please enter the address',
        'enter_area': 'Please enter your area (e.g., part of the city)',
        'enter_street': 'Please enter your street',
        'enter_house': 'Please enter your house number:',
        'summary': "Your full address",
        'subscribed': 'You will receive notifications for the following addresses',
        'list_addresses': 'Listing all your addresses',
        'delete_address': 'Which address would you like to delete?',
        'bye': 'Bye! Hope to talk to you again soon.',
        'invalid_language': 'Invalid language selected. Please try again.',
        'invalid_input': 'Invalid input. Please enter a valid number.',
        'enter_number_delete': 'Please enter the number of the address you want to delete.',
        'address': 'Address',
        'was_deleted': 'was deleted.',
        'address_scheduled_tomorrow': 'There will be a power outage at this address tomorrow.',
        'cancel': 'Cancel',
    },
    'Russian': {
        'welcome': 'Добро пожаловать в бота для электроэнергии Белграда!\nВыберите ваш язык\n',
        'choose_action': 'Пожалуйста, выберите действие:',
        'enter_address': 'Пожалуйста, введите ваш адрес:',
        'enter_area': 'Пожалуйста, введите ваш район (например, часть города):',
        'enter_street': 'Пожалуйста, введите вашу улицу:',
        'enter_house': 'Пожалуйста, введите номер вашего дома:',
        'summary': 'Ваш полный адрес',
        'subscribed': 'Вы будете получать уведомления по следующим адресам',
        'list_addresses': 'Показать все ваши адреса',
        'delete_address': 'Какой адрес вы хотите удалить?',
        'bye': 'До свидания! Надеюсь, мы снова поговорим.',
        'invalid_language': 'Выбран неверный язык. Пожалуйста, попробуйте еще раз.',
        'invalid_input': 'Неверный ввод. Пожалуйста, введите действительный номер.',
        'enter_number_delete': 'Пожалуйста, введите номер адреса, который вы хотите удалить.',
        'address': 'Адрес',
        'was_deleted': 'был удален.',
        'address_scheduled_tomorrow': 'Завтра на этом адресе будет отключение электроэнергии.',
        'cancel': 'Отмена',
    }
}

ACTIONS = {
    'Serbian': {
        'Add Address': 'Додајте адресу',
        'Show All Addresses': 'Покажи све моје адресе',
        'Delete Address': 'Обриши адресу',
    },
    'English': {
        'Add Address': 'Add Address',
        'Show All Addresses': 'Show All Addresses',
        'Delete Address': 'Delete Address',
    },
    'Russian': {
        'Add Address': 'Добавить адрес',
        'Show All Addresses': 'Показать все мои адреса',
        'Delete Address': 'Удалить адрес',
    },
}

SERBIAN_CYRILLIC_ALPHABET = ['А', 'Б', 'В', 'Г', 'Д', 'Ђ', 'Е', 'Ж', 'З', 'И', 'Ј', 'К', 'Л', 'Љ', 'М', 'Н', 'Њ', 'О', 'П', 'Р', 'С', 'Т', 'Ћ', 'У', 'Ф', 'Х', 'Ц', 'Ч', 'Џ', 'Ш']