"""Added bot_language column to the User

Revision ID: a20e78e3b190
Revises: ce5863dc3f2b
Create Date: 2024-11-22 13:28:27.137511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20e78e3b190'
down_revision: Union[str, None] = 'ce5863dc3f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bot_language', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bot_language')
    # ### end Alembic commands ###
